//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncMonitor.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITD_SyncMonitorEntities : DbContext
    {
        public ITD_SyncMonitorEntities()
            : base("name=ITD_SyncMonitorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LS_Customer> LS_Customer { get; set; }
        public virtual DbSet<LS_Employee> LS_Employee { get; set; }
        public virtual DbSet<LS_Lane> LS_Lane { get; set; }
        public virtual DbSet<LS_Shift> LS_Shift { get; set; }
        public virtual DbSet<LS_Station> LS_Station { get; set; }
        public virtual DbSet<LS_TicketType> LS_TicketType { get; set; }
        public virtual DbSet<LS_VehicleType> LS_VehicleType { get; set; }
        public virtual DbSet<SUP_BlackList> SUP_BlackList { get; set; }
        public virtual DbSet<SUP_VehicleInformationManual> SUP_VehicleInformationManual { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
