//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncMonitor.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LS_Customer
    {
        public int CustomerID { get; set; }
        public string CustomerCode { get; set; }
        public string Name { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Telephone { get; set; }
        public string Note { get; set; }
        public bool IsUsed { get; set; }
        public string TaxCode { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string EmployeeCode { get; set; }
        public string IDNo { get; set; }
        public Nullable<short> IsDataFromCenter { get; set; }
        public string BankAccount { get; set; }
        public Nullable<int> IsCompany { get; set; }
        public string Str1 { get; set; }
        public string Str2 { get; set; }
    
        public virtual LS_Employee LS_Employee { get; set; }
    }
}
