//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncMonitor.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LS_Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LS_Employee()
        {
            this.LS_Customer = new HashSet<LS_Customer>();
        }
    
        public int EmployeeID { get; set; }
        public string EmployeeCode { get; set; }
        public string PositionCode { get; set; }
        public string TeamCode { get; set; }
        public string IDNo { get; set; }
        public string ManagerCode { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string NickName { get; set; }
        public Nullable<short> Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Note { get; set; }
        public bool IsUsed { get; set; }
        public Nullable<bool> IsTeamLeader { get; set; }
        public string SmartCardID { get; set; }
        public Nullable<short> IsDataFromCenter { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LS_Customer> LS_Customer { get; set; }
    }
}
