//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncMonitor.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LS_TicketType
    {
        public int TicketTypeID { get; set; }
        public string TicketTypeCode { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public string RouteCode { get; set; }
        public string TicketCategoryCode { get; set; }
        public string VehicleTypeCode { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsMissingCard { get; set; }
        public bool IsUsed { get; set; }
    }
}
