//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncMonitor.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LS_VehicleType
    {
        public int VehicleTypeID { get; set; }
        public string VehicleTypeCode { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> AmountPerKm { get; set; }
        public Nullable<decimal> LowBalance { get; set; }
        public string Note { get; set; }
        public bool IsUsed { get; set; }
    }
}
