//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncMonitor.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITD_SyncMonitorEntities : DbContext
    {
        public ITD_SyncMonitorEntities()
            : base("name=ITD_SyncMonitorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Lane> Lanes { get; set; }
        public virtual DbSet<Station> Stations { get; set; }
        public virtual DbSet<Sync> Syncs { get; set; }
    }
}
