//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncMonitor.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUP_BlackList
    {
        public System.Guid BlackListID { get; set; }
        public string ProductTypeCode { get; set; }
        public string ProductID { get; set; }
        public string EmployeeCode { get; set; }
        public string StationCode { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string ReasonCode { get; set; }
        public Nullable<bool> IsVehicle { get; set; }
        public string Note { get; set; }
        public Nullable<short> IsDataFromCenter { get; set; }
    }
}
