//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncMonitor.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUP_VehicleInformationManual
    {
        public System.Guid VehicleInformationManualID { get; set; }
        public string RegisPlateNumber { get; set; }
        public string AreaCode { get; set; }
        public string VehicleTypeCode { get; set; }
        public Nullable<bool> IsSpecialVehicle { get; set; }
        public string EmployeeCode { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string Note { get; set; }
    }
}
