//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncMonitor.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sync
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string LuongDongBo { get; set; }
        public string Effect { get; set; }
        public long ID_Lane { get; set; }
        public long ID_Station { get; set; }
    
        public virtual Lane Lane { get; set; }
        public virtual Station Station { get; set; }
    }
}
